name: Angular Build

on:
  push:
    branches:
      - master
    # paths:
    #   - 'client/**'
  pull_request:
    branches:
      - master
    # paths:
    #   - 'client/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.16.x'

    # Install Angular CLI
    - name: Install Angular CLI
      run: npm install -g @angular/cli@16.0.0

    # Navigate to Angular app directory
    - name: Navigate to Angular App Directory
      run: cd ./JWTAuth/client

    # Install Angular dependencies
    - name: Install Angular Dependencies
      run: npm install

    # Build Angular app
    - name: Build Angular App
      run: ng build --configuration=production
