name: Angular Build

on:
  push:
    branches:
      - master
    paths:
      - 'clientapp/**'
  pull_request:
    branches:
      - master
    paths:
      - 'clientapp/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.16.x'

    # Install Angular CLI
    - name: Install Angular CLI
      working-directory: ./clientapp
      run: npm install -g @angular/cli@16.0.0

    # Install Angular dependencies
    - name: Install Angular Dependencies
      working-directory: ./clientapp
      run: npm install

    # Build Angular app
    - name: Build Angular App
      working-directory: ./clientapp
      run: ng build --configuration=production
