name: .NET and Angular Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    # Restore and build .NET project
    - name: Restore and Build .NET API
      working-directory: ./API
      run: |
        dotnet restore
        dotnet build --no-restore

    # Test .NET project
    - name: Test .NET API
      working-directory: ./API
      run: dotnet test --no-build --verbosity normal

    # Install Node.js and npm
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    # Install Angular CLI
    - name: Install Angular CLI
      run: npm install -g @angular/cli

    # Navigate to Angular app directory
    - name: Navigate to Angular App Directory
      working-directory: ./client

    # Install Angular dependencies
    - name: Install Angular Dependencies
      run: npm install

    # Build Angular app
    - name: Build Angular App
      run: ng build --configuration=production
