name: .NET Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./API
      run: dotnet restore
    - name: Build
      working-directory: ./API
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./API
      run: dotnet test --no-build --verbosity normal

  trigger_angular_build:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Trigger Angular Build Workflow
      uses: actions/github-script@0.10.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: workflows } = await github.actions.listRepoWorkflows();
          const angularBuildWorkflow = workflows.find(workflow => workflow.name === 'Angular Build');
          if (angularBuildWorkflow) {
            await github.actions.createWorkflowDispatch({
              workflow_id: angularBuildWorkflow.id
            });
          }
